# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bed985b57bfa5c78a396e6964fba62a9b1dc51c4b433a7bae2437d7e0121dba5ed5225f9214c0984a60f9e7bf9dc8e74bb30931367e4723b6a320525a673879

test:
  secret_key_base: 0df3926dbe5e1d07231b068dc3df46ffc2bfecf1ce2e74fc4499dff67b412561f84f2cbdc13954c3f081bb27bf3488c736240caf5fd4ff8f071df67839750bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
